#!/usr/bin/env python3
"""
generate_bing_voice_catalog.py

Converts a Bing/Azure Neural TTS voice list (the same shape as the JSON you get
back from the "List voices" endpoint / TranslateWebPage's voice table) into a
plain-data C++ header that QOnlineTranslator's BingVoiceCatalog consumes at
runtime.

Why generate instead of hand-maintaining the table:
  - Microsoft adds/renames/removes voices periodically; regenerating from a
    fresh JSON export is a one-liner instead of a hand-edited C++ diff.
  - The generated header intentionally contains NO logic - just a flat array
    of {name, locale, country, language, gender}. All grouping (language ->
    country -> gender -> voice) and every edge case (Cantonese, Traditional
    Chinese aliasing, etc.) live in bingvoicecatalog.cpp, which is hand
    maintained and does NOT need to change when you regenerate this file.

Usage:
    python3 generate_bing_voice_catalog.py bing-tts-voice-table.json \
        -o ../src/qonlinetranslator/bingvoicecatalog_data.h

Input JSON shape (array of objects), matching Microsoft's own field names:
    [
      {
        "name": "af-ZA-AdriNeural",
        "locale": "af-ZA",
        "country": "South Africa",
        "language": "Afrikaans",
        "gender": "Female"
      },
      ...
    ]

Both "locale" and "name" are required; missing/empty rows are skipped with a
warning printed to stderr so a bad export doesn't silently produce a broken
(or truncated) catalog.
"""

import argparse
import json
import sys
from datetime import datetime, timezone

REQUIRED_FIELDS = ("name", "locale", "country", "language", "gender")

HEADER_TEMPLATE = """\
// Auto-generated by tools/generate_bing_voice_catalog.py - DO NOT EDIT BY HAND.
//
// Source:     {source}
// Generated:  {generated}
// Voice count: {count}
//
// Regenerate with:
//   python3 tools/generate_bing_voice_catalog.py {source} 
//       -o src/qonlinetranslator/bingvoicecatalog_data.h
//
// This file is intentionally dumb data: BingVoiceCatalog (hand written) is
// responsible for turning these flat rows into the language/country/gender
// hierarchy the settings dialog needs, and for handling any naming edge
// cases (Cantonese, Traditional Chinese, ...). Nothing here should ever need
// per-language logic - if it does, that logic belongs in
// bingvoicecatalog.cpp instead, so it survives the next regeneration.

#ifndef BINGVOICECATALOG_DATA_H
#define BINGVOICECATALOG_DATA_H

namespace BingVoiceCatalogData {{

struct RawVoiceEntry {{
    const char *name;
    const char *locale;
    const char *country;
    const char *language;
    const char *gender;
}};

inline constexpr RawVoiceEntry kVoices[] = {{
{rows}
}};

inline constexpr int kVoiceCount = sizeof(kVoices) / sizeof(kVoices[0]);

}} // namespace BingVoiceCatalogData

#endif // BINGVOICECATALOG_DATA_H
"""


def escape(value: str) -> str:
    """Escape a string for use inside a C++ string literal."""
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def load_entries(path: str):
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        sys.exit(f"error: {path} must contain a JSON array of voice entries")

    entries = []
    for i, raw in enumerate(data):
        missing = [field for field in REQUIRED_FIELDS if not raw.get(field)]
        if missing:
            print(
                f"warning: skipping entry {i} (missing/empty fields: {', '.join(missing)}): {raw}",
                file=sys.stderr,
            )
            continue
        entries.append({field: str(raw[field]) for field in REQUIRED_FIELDS})

    return entries


def render(entries, source: str) -> str:
    # Sorted for a stable, readable diff between regenerations.
    entries = sorted(entries, key=lambda e: (e["language"], e["locale"], e["gender"], e["name"]))

    rows = []
    for e in entries:
        rows.append(
            "    {{\"{name}\", \"{locale}\", \"{country}\", \"{language}\", \"{gender}\"}},".format(
                name=escape(e["name"]),
                locale=escape(e["locale"]),
                country=escape(e["country"]),
                language=escape(e["language"]),
                gender=escape(e["gender"]),
            )
        )

    return HEADER_TEMPLATE.format(
        source=source,
        generated=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        count=len(entries),
        rows="\n".join(rows),
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("input", help="Path to bing-tts-voice-table.json")
    parser.add_argument(
        "-o",
        "--output",
        default="bingvoicecatalog_data.h",
        help="Output header path (default: %(default)s)",
    )
    args = parser.parse_args()

    entries = load_entries(args.input)
    if not entries:
        sys.exit("error: no valid voice entries found - nothing to generate")

    header = render(entries, args.input)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"Wrote {len(entries)} voice entries to {args.output}")


if __name__ == "__main__":
    main()
