// Auto-generated by tools/generate_bing_voice_catalog.py - DO NOT EDIT BY HAND.
//
// Source:     sample-bing-tts-voice-table.json
// Generated:  2026-09-05 04:23 UTC
// Voice count: 38
//
// Regenerate with:
//   python3 tools/generate_bing_voice_catalog.py sample-bing-tts-voice-table.json \
//       -o src/qonlinetranslator/bingvoicecatalog_data.h
//
// This file is intentionally dumb data: BingVoiceCatalog (hand written) is
// responsible for turning these flat rows into the language/country/gender
// hierarchy the settings dialog needs, and for handling any naming edge
// cases (Cantonese, Traditional Chinese, ...). Nothing here should ever need
// per-language logic - if it does, that logic belongs in
// bingvoicecatalog.cpp instead, so it survives the next regeneration.

#ifndef BINGVOICECATALOG_DATA_H
#define BINGVOICECATALOG_DATA_H

namespace BingVoiceCatalogData {

struct RawVoiceEntry {
    const char *name;
    const char *locale;
    const char *country;
    const char *language;
    const char *gender;
};

inline constexpr RawVoiceEntry kVoices[] = {
    {"af-ZA-AdriNeural", "af-ZA", "South Africa", "Afrikaans", "Female"},
    {"af-ZA-WillemNeural", "af-ZA", "South Africa", "Afrikaans", "Male"},
    {"am-ET-MekdesNeural", "am-ET", "Ethiopia", "Amharic", "Female"},
    {"am-ET-AmehaNeural", "am-ET", "Ethiopia", "Amharic", "Male"},
    {"zh-CN-XiaoxiaoNeural", "zh-CN", "China", "Chinese", "Female"},
    {"zh-CN-YunxiNeural", "zh-CN", "China", "Chinese", "Male"},
    {"zh-HK-HiuGaaiNeural", "zh-HK", "Hong Kong", "Chinese (Cantonese)", "Female"},
    {"zh-HK-WanLungNeural", "zh-HK", "Hong Kong", "Chinese (Cantonese)", "Male"},
    {"en-AU-NatashaNeural", "en-AU", "Australia", "English", "Female"},
    {"en-AU-WilliamNeural", "en-AU", "Australia", "English", "Male"},
    {"en-GB-SoniaNeural", "en-GB", "United Kingdom", "English", "Female"},
    {"en-GB-RyanNeural", "en-GB", "United Kingdom", "English", "Male"},
    {"en-IN-NeerjaNeural", "en-IN", "India", "English", "Female"},
    {"en-IN-PrabhatNeural", "en-IN", "India", "English", "Male"},
    {"en-US-AriaNeural", "en-US", "United States", "English", "Female"},
    {"en-US-JennyNeural", "en-US", "United States", "English", "Female"},
    {"en-US-GuyNeural", "en-US", "United States", "English", "Male"},
    {"fr-CA-SylvieNeural", "fr-CA", "Canada", "French", "Female"},
    {"fr-CA-JeanNeural", "fr-CA", "Canada", "French", "Male"},
    {"fr-FR-DeniseNeural", "fr-FR", "France", "French", "Female"},
    {"fr-FR-HenriNeural", "fr-FR", "France", "French", "Male"},
    {"de-AT-IngridNeural", "de-AT", "Austria", "German", "Female"},
    {"de-AT-JonasNeural", "de-AT", "Austria", "German", "Male"},
    {"de-DE-KatjaNeural", "de-DE", "Germany", "German", "Female"},
    {"de-DE-ConradNeural", "de-DE", "Germany", "German", "Male"},
    {"it-IT-ElsaNeural", "it-IT", "Italy", "Italian", "Female"},
    {"it-IT-IsabellaNeural", "it-IT", "Italy", "Italian", "Female"},
    {"it-IT-DiegoNeural", "it-IT", "Italy", "Italian", "Male"},
    {"ja-JP-NanamiNeural", "ja-JP", "Japan", "Japanese", "Female"},
    {"ja-JP-KeitaNeural", "ja-JP", "Japan", "Japanese", "Male"},
    {"es-ES-ElviraNeural", "es-ES", "Spain", "Spanish", "Female"},
    {"es-ES-AlvaroNeural", "es-ES", "Spain", "Spanish", "Male"},
    {"es-MX-DaliaNeural", "es-MX", "Mexico", "Spanish", "Female"},
    {"es-MX-JorgeNeural", "es-MX", "Mexico", "Spanish", "Male"},
    {"es-US-PalomaNeural", "es-US", "United States", "Spanish", "Female"},
    {"es-US-AlonsoNeural", "es-US", "United States", "Spanish", "Male"},
    {"vi-VN-HoaiMyNeural", "vi-VN", "Vietnam", "Vietnamese", "Female"},
    {"vi-VN-NamMinhNeural", "vi-VN", "Vietnam", "Vietnamese", "Male"},
};

inline constexpr int kVoiceCount = sizeof(kVoices) / sizeof(kVoices[0]);

} // namespace BingVoiceCatalogData

#endif // BINGVOICECATALOG_DATA_H
